# -*- coding: utf-8 -*-
"""Task_4_heart_disease.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EAO41fnO82KjpyllkMnVrlHLvKDHwF_c
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier

df = pd.read_csv('/content/heart_disease.csv')

df.info()
# there is no encoding

df.describe()
# the boxplot

df.isnull().sum()

corr = df.corr()
plt.figure(figsize=(12, 8))
sns.heatmap(
    corr,
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    linewidths=0.5
)
plt.title("Correlation Heatmap")
plt.show()

for col in ["chol", "trestbps", "oldpeak", "thalach"]:
    Q1 = df[col].quantile(.25)
    Q3 = df[col].quantile(.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    df[col] = df[col].clip(lower, upper)

df.describe()

df.duplicated().sum()

df.drop_duplicates(inplace=True)

X = df.drop("target", axis=1)
y = df["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2, random_state=20)

model = RandomForestClassifier( n_estimators=300, max_depth=6, class_weight="balanced",random_state=20)
model.fit(X_train , y_train)
y_pred = model.predict(X_test)

y_train_pred = model.predict(X_train)
# leave the train acc

print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

model = XGBClassifier(n_estimators= 200, max_depth=4,random_state= 20)

model.fit(X_train, y_train)
y_test_pred = model.predict(X_test)

print(accuracy_score(y_test, y_test_pred))
print(confusion_matrix(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred))

model = DecisionTreeClassifier( max_depth=5, random_state= 20)

model.fit(X_train, y_train)

y_test_pred = model.predict(X_test)

print( accuracy_score(y_test, y_test_pred))
print(confusion_matrix(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred))