# -*- coding: utf-8 -*-
"""Task_3_Teen_Mental_Health.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wKdpoTRTj08b8QR86MWljmLsCwX3WWkW
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

df = pd.read_csv('/content/Teen_Mental_Health_Dataset.csv')

df.info()

df.describe()

df.isnull().sum()

df.duplicated().sum()

le = LabelEncoder()

for col in df.select_dtypes(include=['object']).columns:
   df[col] = le.fit_transform(df[col])

df.describe()

df.info()

corr = df.corr(numeric_only=True)
plt.figure(figsize=(12,8))

sns.heatmap(
    corr,
    annot=True,
    cmap="coolwarm",   # better color palette
    linewidths=0.5,
    fmt=".2f"
)

plt.title("Correlation Heatmap")
plt.show()

"""Logistic regression predicting the depression label"""

x = df.drop('depression_label', axis =1)
y = df['depression_label']

X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = LogisticRegression()
model.fit(X_train, y_train)

y_train_pred = model.predict(X_train)
print("Training Accuracy:", accuracy_score(y_train, y_train_pred))
print(classification_report(y_train, y_train_pred))

y_pred = model.predict(X_test)

print("Test Accuracy", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))